server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hm-dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.101.130
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: dianping
    password: 1234
    listener:
      simple:
        prefetch: 1 # 每次只能拿一条信息，处理完后才能继续获取下一条信息
        concurrency: 1
        max-concurrency: 1 # 只有一个线程消费信息
        acknowledge-mode: manual # 手动确认
    virtual-host: /dianping
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug